### PR TITLE
Crop Growth Restrictions, v2

### PR DESCRIPTION
**Pull request by vishtheshnu**
I made all of the changes specified, including changing the formatting and the default options for configurations. Other configurations were removed (tall grass), and greenhouse glass now allows crops below it to grow in any season. I assumed greenhouse glass works as a means of insulation, so if there is greenhouse glass within a configurable height above the plant, then it will be fertile, even if there are things in the way, or the glass has other opaque blocks above it. I also implemented tooltips for listed crops that show which seasons they're fertile in.

### CODE REVIEW

**Comment by Forstride** [comment]
I'm just gonna merge this for the time being and mess around with it to get a better feel of what needs to be changed.  Will post again with any other issues or changes that need to be made.

**Comment by vishtheshnu** [comment]
Great! Let me know if there's anything else I can change when it comes up.

**Comment by Forstride** [comment]
One thing I'm kind of confused about, is that this doesn't seem to actually be checking for the seed item of the crops.  It's like it's only checking if the config list happens to have the name of the crop included somewhere (So like, melons would check for "melon", and happen to see "melon_seeds" allowing it to work).

Anyway, I made it so this only affects blocks that extend BlockCrops, which was what I originally wanted it to be like, although I'm not sure if you can actually check the seed item, since it seems to be protected in BlockCrops.

**Comment by vishtheshnu** [comment]
What I did was allow the player to list the seed names, and the code would
get the equivalent plant from that in the preinit method. If something
tried to grow and it was a plant, it would check to see if that plant was
stored in the proper season HashSet and allow it to grow if it was in there.

Your change sounds good, but it might not affect saplings anymore, though.

**Comment by Forstride** [comment]
So, this isn't actually an issue with the PR necessarily, but I noticed with Simple Corn, bonemeal doesn't work on them out of season, but they'll still grow naturally out of season for some reason.

It doesn't seem like they actually use the Forge grow hooks, so I'm wondering if you have any possible ideas for some kind of failsafe for mods that don't set up their crops properly.  Maybe setting them to not tick randomly if that's possible?

**Comment by vishtheshnu** [comment]
Which mod is Simple Corn from? I'll check out what the deal with that is.

**Comment by Forstride** [comment]
The mod itself is called Simple Corn.  I already know what the issue is, but like I said, I was wondering if you had any ideas for maybe coming up with a workaround to still allow it to work.

**Pull request merged**
