### PR TITLE
Forge & Fabric 1.20.1 Backport

### PR DESCRIPTION
**Pull request by marlester-dev**
Backported to 1.20.1 Forge & Fabrik
The basis for this backport was 1.20.4-multi branch

### CODE REVIEW

**Comment by marlester-dev** [comment]
@Adubbz thank you for merging the BOP PR. please review this PR for Serene Seasons.

**Comment by Adubbz** [comment]
I have no issue with NeoForge being removed for 1.20.1, however Forge should remain. If this is going to take over as the definitive 1.20.1 branch it should account for both.

**Comment by Adubbz** [comment]
Also, broadly speaking, a substantive amount of changes are unnecessary shuffling around of imports or indentation changes. Please ensure your style matches the existing code, and minimize the making of changes where they aren't needed.

**Comment by marlester-dev** [comment]
> I have no issue with NeoForge being removed for 1.20.1, however Forge should remain. If this is going to take over as the definitive 1.20.1 branch it should account for both.


Alright, fair enough. Then I would need to update GlitchCore one more time to develop ConfigSync for forge. I just deleted forge to reduce the time needed for development and bug testing. I will make this PR a draft one more time.
> Also, broadly speaking, a substantive amount of changes are unnecessary shuffling around of imports or indentation changes. Please ensure your style matches the existing code, and minimize the making of changes where they aren't needed.


Sorry, it seems like my idea changed the indentation accidentally. I will turn it back to normal.

**Pull request merged**
