### PR TITLE
Ported code for offline season simulation from TAN.

### PR DESCRIPTION
**Pull request by Avatair**
This change allows to simulate weather effects (like snowing, melting or freezing) in chunks which are not loaded and generated and thus makes season weather effects happen globally. It introduces some changes in chunk loading/generation handling.

A journal of happened weather events, like season changing and raining is recorded and replayed on older and newly generated chunks by a patching mechanism. To perform this, new information has to be stored in season data. It contains the journal data and time stamp values per chunk of their last updates.

### Things to be done:
* _Crop death simulation_: The chunk patcher must be extended to handle crop deaths during cold seasons. When introducing this change, villagers should be adapted to replant dead crops.

### Known Bugs:
* _Balance_: Melting at offline chunks are too fast compared to melting by chunk ticks resulting in seams when travelling far away.

### Test version:
To enable the feature edit "Enable Global Frost"=true in seasons.cfg 
**This feature is in alpha stage! Back up your world first before using to avoid losing data!**
[SereneSeasons-1.12.2-1.2.6.null-universal.jar-2018-09-30-R2.zip](https://github.com/Glitchfiend/SereneSeasons/files/2431492/SereneSeasons-1.12.2-1.2.6.null-universal.jar-2018-09-30-R2.zip)

### CODE REVIEW

**Comment by Brycey92** [comment]
If several season cycles pass, will the unloaded chunks replay all recorded actions, or just the ones required to get from their last season to the current season?

**Comment by Avatair** [comment]
Not all the entries. Only the recent ones. There is a constant SeasonChunkPatcher.RETROSPECTIVE_WINDOW_TICKS how far it should look back from the present to replay the journal. Actually it is set on 9 Minecraft days.

**Comment by RomaXYZ** [comment]
Are you sure that this feature still works in the latest version of the mod? Or do you have to wait a while before it takes effect?

**Comment by Forstride** [comment]
Ehm...It hasn't been merged into the mod yet.  I really haven't had time to test it, and it's so complex that I wouldn't be able to handle any possible issues it might have myself.

Really not sure what we're going to do with it

**Comment by RomaXYZ** [comment]
I completely understand, I know that programming can be a very tedious and frustrating process... but if this code does make its way into the mod it would be a REALLY nice feature and would really build an ambiance of reality in Minecraft. Many people who play Minecraft don't hunker down in one base and don't explore, they venture out. Whenever people travel to far away lands during the winter, seeing that snow hasn't fallen really just destroys the ambiance. I know that it is hard, I know it is complex. If ya'll think you could make the mod better using an alternative way that uses less resources then do it. But, if ya'll are able to pull this off... kuddos

**Comment by Avatair** [comment]
I could do a little javadoc documentation for it to make it better understandable.

**Comment by Avatair** [comment]
If you need more people, then I could offer help in testing as well as in bugfixing for some time to release this feature earlier. Actually I'm busy with another MC mod myself, but could yield a little time for this PR. I can also add switch for the config to be able to turn off global chunk patching as this feature would be actually in an alpha state.

Most of the performance issues have been fixed. Altough the changes haven't been tested on servers with more players. Also integrity with other mods hasn't been explored, yet.

**Comment by RomaXYZ** [comment]
I am in control of a server, if ya'll want a tester... I could do it for ya'll

**Comment by RomaXYZ** [comment]
Alright I’ll report back with the results

**Comment by RomaXYZ** [comment]
The mod seems to be holding up pretty well, however, this might have nothing to do with the feature but what I've noticed is that sometimes whenever I leave the server on for a prolonged period of time... the seasons seem to decouple with the season's clock and the clock is useless in finding seasons. Another thing is that the game calculates that its winter and so it snows and theres snow in the ground but its rain thats falling. Another thing is that, i'm not sure if ya'll added something to prevent oceans from freezing over during the winter... but ya'll should add something that prevents that if ya'll didn't.

**Comment by Avatair** [comment]
In which biome is it raining while snow is accumulating on ground?

**Comment by Avatair** [comment]
With the clock and rain issues I found a thread conflict on time synchronization. Different threads are modifying SeasonHandler.clientSeasonCycleTicks at the same time.

**Comment by Forstride** [comment]
"i'm not sure if ya'll added something to prevent oceans from freezing over during the winter"

the way ices forms is by checking for solid blocks, so it starts freezing at the edge of a body of water and goes inward.  the chances that an entire ocean will freeze from that is very unlikely

**Comment by RomaXYZ** [comment]
Yeah I figured that out pretty quickly so I made sure everyone in the server had the same config sereneseasons file as me and I uploaded my config file into the server so that it all matches.

**Comment by Forstride** [comment]
Would you be able to fix the conflicts made by recent changes?  I think I'm finally ready to take a look at this and try to integrate it with the mod, as I've noticed issues with snow appearing in new chunks during the Winter, and it's kind of awkward with it staying there if you leave the chunks and come back in a different season.

**Comment by Forstride** [comment]
Additionally, there's gonna need to be some kind of way to completely disable this.  I don't know exactly how taxing it is, but if it's bad enough on lower end PCs/servers, there should be a way to disable it.

**Comment by Avatair** [comment]
I've seen that there are a lot of changes in the past 48 hours. Is it expected more to come? If yes, then it is better to wait before merging.

For the ability to disable the feature there exists already the "Enable Global Frost" property, which has maybe a little confusing name, but it simply disables global season change effects.

**Comment by Forstride** [comment]
Melting is also disabled with Generate Snow and Ice set to false.  You should just use that option and remove the Global Frost one

**Comment by Avatair** [comment]
The merging is more complicated now, since I moved methods from SeasonASMHelper to SeasonHelper to allow additional arguments. Also changes were made to same methods from your side. I'm not sure I'll be able to merge it on my own without breaking your stuff. Following methods are impacted:
- SeasonASMHelper.canSnowAtInSeason
- SeasonASMHelper.canBlockFreezeInSeason
- SeasonASMHelper.getFloatTemperature

Can you apply your changes first to my branch for the three methods above? I'm open if you have any questions.

The second thing is, that I also introduced SeasonHelper.modifyTemperature to fix raining in winter in some biomes. A solution is needed for this as well. Either remove it completely and replace by your version or merge both things somehow.

**Comment by Forstride** [comment]
I mean those are pretty much the core things that I changed.  The stuff that you added to SeasonHelper really shouldn't be needed anymore.  Technically the snow/ice stuff doesn't even go by the season anymore, and instead solely goes by the modified temperate (from getFloatTemperature).  All of the snow and ice generation is completely done by vanilla's own functions now, and all we have to do is the melting for it in when it gets warm enough, since vanilla doesn't do that at all.

I suppose I could change getFloatTemperature to allow for a season argument though.  Would that work?

"fix raining in winter in some biomes"

I fixed that the other day (At least it should be fixed from what I tested).  Before it was an issue of certain spots having slightly too high of a temperature due to the temperature noise, but I changed it back to check the default biome temperature rather than the specific temperature at that block.

**Comment by Avatair** [comment]
Well, more things are needed than only melting, because vanilla MC only applies snow to new chunks, but doesn't touch the already generated ones. So the patcher needs to update chunks if they get loaded. Also it processes loaded chunks which are far away from player, because they aren't updated by MC vanilla as well during snow fall.

For the both methods which could be removed: The method ChunkPatcher.executePatchCommand(int, int, Chunk) is dependent on both boolean methods to determine how to update a block. If only getFloatTemperature is relevant then they need to be substituted there in dependence of the temperature. Yes, a season dependent argument would be needed since ChunkPatcher.executePatchCommand is passing it independently from the current season, when replaying the recorded journal on a chunk. A journal could span over multiple seasons.

If you fixed the raining issue in winter, then better use your changes instead.

**Comment by Forstride** [comment]
"because vanilla MC only applies snow to new chunks"

Well I meant, the actual snowfall and ice generation in loaded biomes is just done by vanilla, but using our overriding methods to check if it can snow.  Anyway, I'll get the season argument added to getFloatTemperature and hopefully things will be all set

**Comment by Forstride** [comment]
Alright, should be good to go now.  Adubbz added a separate method in BiomeHooks that allows you to get the modified temperature of a biome for whatever season you provide.

**Comment by Forstride** [comment]
There's a Forge hook for the snow/ice generation in new chunks in ChunkGeneratorOverworld.  Could just cancel that for biomes that aren't permanently snowy.

**Comment by Avatair** [comment]
Also, it is needed to prevent ocean from freezing. The method SeasonHelper.canBlockFreezeInSeason is called by the patcher to do freezing globals. So this one needs a biome check or something like.

**Comment by Forstride** [comment]
The ocean and river biomes are already blacklisted from freezing.

**Comment by Forstride** [comment]
Also ignore what I said about the Forge event.  There's no way to check the biome, and it decorates the entire chunk at once.  So we'll have to either use ASM or go back to the old method.  I'll talk to Adubbz again and see what he can do.

**Comment by Avatair** [comment]
Maybe it helps. There is another PR about dimension blacklisting. There I fought with ASM already and also added blacklisting to things like foliage color and not only the block updates. You can find it here: https://github.com/Glitchfiend/SereneSeasons/pull/91

**Comment by IdrisQe** [comment]
So, just curious, what's the status on this? It's been almost a year and progress seems to have just halted on this PR.

**Comment by Brycey92** [comment]
I'm still curious as to the status of this as well.

**Pull request closed without merging**
