### PR TITLE
Default Fertility Config Update, for 1.14 branch WIP

### PR DESCRIPTION
**Pull request by NillerMedDild**
This PR updates the Fertility Config to match the 1.15.1 version, if #219 is accepted.
I realize you don't support 1.14, so I understand if you simply close this.

### CODE REVIEW

**Comment by Forstride** [comment]
Updated it myself to match the changes I made, so I'm just gonna close this.

**Comment by FiammaVerde** [comment]
Fertility on Simple Farming seeds is not showing up in 1.14.4-2.0.0.40 (latest CurseForge version).

**Comment by Forstride** [comment]
Yes, it's an issue with all modded crops.  Just waiting for @Adubbz to fix it eventually

**Comment by FiammaVerde** [comment]
Thanks for the super fast reply & your modding work!

If I understand correctly, the Simple Farming seeds will respect Serene Seasons if both mods are installed in 1.14.4? (I do see the entries in fertility.toml)

**Pull request closed without merging**
