### PR TITLE
Simple Farming Fertility Entries WIP

### PR DESCRIPTION
**Pull request by NillerMedDild**
This PR adds Simple Farming seeds, bushes and saplings to the default configs.

### CODE REVIEW

**Comment by Forstride** [comment]
Just curious why you put a bunch of their crops in Winter.  I mean I'm not opposed to having support for it, but I'd kind of prefer the default configs to all be fairly similar as far as what can grow in each season.  So like, their carrots should match vanilla carrot seasons, and other seeds should try to match what the HarvestCraft seeds are set to, cause I went through all of those and made sure they were appropriate for each season (Mostly based on Stardew Valley's crops, as well as real-world crop seasons)

**Comment by NillerMedDild** [comment]
I based it on real-world crop seasons, the ones in Winter can survive mild frost. My google-fu when it comes to crop seasons probably isn't the best, so I may have gotten some of these wrong :P

**Comment by Forstride** [comment]
Keep in mind, growing stuff in Winter IRL would probably still require a greenhouse or some other form of protection.  This is meant to be if they were just grown out in the open with no protection or anything.

Aside from that, we just generally treat Winter as a harsh season where pretty much nothing can grow aside from trees (Since trees can grow pretty high, it's a bit tricky to require greenhouse glass for them in the Winter).

**Comment by NillerMedDild** [comment]
Myeah true, I suppose just being able to survive winter shouldn't allow them to grow in SS, I'll modify the PR.

The trees I added to the summer list are crop-trees, where the leaves grow fruit, would you prefer those are moved to the winter list?

**Comment by Forstride** [comment]
If they're specifically crop trees then no, it'd probably make sense to keep those in proper seasons.

**Comment by NillerMedDild** [comment]
Matching seeds to the harvestcraft ones is gonna take a while, so I'm marking the PR WIP and coming back to finish it later.

**Comment by Forstride** [comment]
I can do it myself.  I'll just merge this for now.

**Comment by NillerMedDild** [comment]
Thank you :D

**Pull request merged**
